### ISSUE TITLE
Proxy Feature Progress Tracking

### ISSUE THREAD

**Issue by IgnoredAmbience** [jscert/jsexplain#3]
Checklist of items todo:
* [x] Create new object internal slots
* [x] Create types for new object internal functions
* [ ] Implement/check existing implementation of spec functions referenced by new internal functions
  * [x] OrdinaryGetPrototypeOf(O)
  * [x] OrdinarySetPrototypeOf(O,V)
  * [x] OrdinaryIsExtensible(O)
  * [x] OrdinaryPreventExtensions(O)
  * [x] `OrdinaryHasProperty(O,P)`
  * [ ] ~OrdinaryOwnPropertyKeys(O)~ correct key ordering not yet implemented
    * [ ] EnumerableOwnPropertyNames
      * [ ] Object.keys
    * [ ] ObjectDefineProperties
      * [ ] Object.defineProperties
  * [x] ~`Type(handler)`~ special-cased due to type safety of OCaml (and implemented)
  * [x] `IsCallable(argument)`
  * [x] `IsConstructable(argument)`
  * [x] GetV
  * [x] `GetMethod(handler, "getPrototypeOf")`
  * [x] `Call(trap, handler, <<target>>)`
  * [x] `Construct(...)`
  * [x] `IsExtensible(target)`
  * [x] `SameValue(x, y)`
  * [x] `SameValueNonNumber(x, y)`
  * [x] `ToBoolean(x)`
  * [x] `Get(O,P)`
  * [x] `HasProperty(O,P)`
  * [x] `ToPropertyDescriptor(x)`
  * [x] `CompletePropertyDescriptor(x)`
  * [x] `IsCompatiblePropertyDescriptor(x, y, z)`
  * [x] `ValidateAndApplyPropertyDescriptor(O,P,x,y,z)`
  * [x] `OrdinaryDefineOwnProperty(O, P, Desc)`
  * [x] `OrdinaryGetOwnProperty(O, P)`
  * [x] `FromPropertyDescriptor(x)`
  * [x] `IsPropertyKey(P)`
  * [x] `IsDataDescriptor(D)`
  * [x] `IsAccessorDescriptor(D)`
  * [x] `CreateListFromArrayLike(A, <<String, Symbol>>)`
  * [x] `CreateArrayFromList(L)`
  * [x] `OrdinarySet(O,P,V,Receiver)`
  * [x] `CreateDataProperty(O,P,V)`
  * [x] `PutValue(V,W)`
  * [x] `Set(O,P,V,Throw)`
    * [x] References
      * [x] GetBase
      * [x] GetReferencedName
      * [x] IsStrictReference
      * [x] HasPrimitiveBase
      * [x] IsPropertyReference
      * [x] IsUnresolvableReference
      * [x] IsSuperReference
      * [x] GetValue
      * [x] GetThisValue
    * [x] Object Environment records
      * [x] GetBindingValue
      * [x] SetMutableBinding
  * [x] `OrdinaryGet(O,P,Receiver)`
* [x] Implement dispatchers to correct variant of Object internal functions *(compatibility wrapper to dispatch between ES5/ES6 spec calling conventions)*
  * [x] `[[GetPrototypeOf]]`
  * [x] `[[SetPrototypeOf]]`
  * [x] `[[IsExtensible]]`
  * [x] `[[PreventExtensions]]`
  * [x] `[[GetOwnProperty]]`
  * [x] `[[DefineOwnProperty]]`
  * [x] `[[HasProperty]]`
  * [x] `[[Get]]`
  * [x] `[[Set]]`
  * [x] `[[Delete]]`
  * [x] `[[OwnPropertyKeys]]`
  * [x] `[[Call]]`
  * [x] `[[Construct]]`
* [x] Implement new/Update existing Ordinary Object internal functions
  * [x] `[[GetOwnProperty]]`
  * [x] `[[DefineOwnProperty]]`
  * [x] `[[HasProperty]]`
  * [x] `[[Get]]`
  * [x] `[[Delete]]`
  * [x] `[[GetPrototypeOf]]`    (new accessor to `[[Prototype]]` internal property)
  * [x] `[[SetPrototypeOf]]`    (new accessor to `[[Prototype]]` internal property)
  * [x] `[[IsExtensible]]`      (new accessor to `[[Extensible]]` internal property)
  * [x] `[[PreventExtensions]]` (new accessor to `[[Extensible]]` internal property)
  * [x] `[[Set]]`               (renamed from `[[Put]]`??)
  * [x] `[[OwnPropertyKeys]]` (implemented, but using stubbed `OrdinaryOwnPropertyKeys`)
* [x] Implement handlers for Proxy Object internal functions
  * [x] `[[GetPrototypeOf]]`
  * [x] `[[SetPrototypeOf]]`
  * [x] `[[IsExtensible]]`
  * [x] `[[PreventExtensions]]`
  * [x] `[[GetOwnProperty]]`
  * [x] `[[DefineOwnProperty]]`
  * [x] `[[HasProperty]]`
  * [x] `[[Get]]`
  * [x] `[[Set]]`
  * [x] `[[Delete]]`
  * [x] `[[OwnPropertyKeys]]`
  * [x] `[[Call]]`
  * [x] `[[Construct]]`
* [x] Rehook existing ES5 methods to use new ES7 constructs
  * [x] Object.preventExtensions(O)
  * [x] Object.isExtensible(O)
  * [x] Object.seal(O)
  * [x] Object.setPrototypeOf
  * [x] Object.isSealed
  * [x] Object.isFrozen
  * [x] Object.freeze
  * [x] `[[GetPrototypeOf]]`
    * [x] Object.getPrototypeOf(O)
    * [x] Object.prototype.isPrototypeOf(v)
    * [x] Function `[[HasInstance]]`
    * [x] Array.prototype.sort
  * [x] `[[SetPrototypeOf]]`
  * [x] `[[IsExtensible]]`
  * [x] `[[PreventExtensions]]`
  * [x] `[[GetOwnProperty]]`
  * [x] `[[DefineOwnProperty]]`
  * [x] `[[HasProperty]]`
  * [x] `[[Get]]`
  * [x] `[[Set]]`
  * [x] `[[Delete]]`
  * [ ] `[[OwnPropertyKeys]]`
    * [ ] Object.defineProperties (via ObjectDefineProperties)
    * [ ] Object.keys (via EnumerableOwnPropertyNames)
  * [x] `[[Call]]`
  * [x] `[[Construct]]`
* [x] Miscellaneous ES6/7 changes as required (to be listed)
* [x] Proxy global object
  * [x] Proxy constructor
  * [x] Proxy.revocable
    * [x] Proxy revocation function constructor ([26.2.2.1](https://tc39.github.io/ecma262/2017/#sec-proxy.revocable))
    * [x] Proxy revocation function body
* [x] Install Proxy constructor/functions to heap
* [x] Final bugfixing of jsjsref
  * [x] #13 reserved keywords need rewriting for js output
  * [x] f4a3cfd avoid using `===` as a higher-order function
  * [x] 07f480c & d003223 shadowed variables output fixed
  * [x] implement `_compare_*` functions
* [x] Testing against modern test262
  * [x] `[[GetOwnProperty]]` (ordinary objects)
  * [x] `[[DefineOwnProperty]]` (ordinary objects)

**Comment by IgnoredAmbience** [comment]
See also tc39/ecma262#1030

**Comment by IgnoredAmbience** [comment]
As of 3fe79d4 all Proxy tests are passing or skipped due to not implemented features. This set of features needs to be checked and refined.

**Comment by IgnoredAmbience** [comment]
As of 052a662 all Proxy tests are passing, except for ones skipped due to unimplemented features:
* Symbol
* cross-realm
* `Object.create`
* anything involving property iteration or ordering
* `[[Construct]]` where `O` and `newTarget` differ (due to classes)
* `new.target`

Reflect has now been implemented and fully tested as working.

A few tests that use `new.target` will not be skipped until tc39/test262#1648 lands and we update the test262 submodule.

**Comment by brabalan** [comment]
I think we should merge this to master.

**Comment by IgnoredAmbience** [comment]
Remaining incomplete features (property enumeration order) are now tracked in #28.
